const assert = require('node:assert/strict');
const fs = require('node:fs');
const vm = require('node:vm');
const ts = require('typescript');
assert.ok(fs.existsSync('loan-options.ts'), 'Loan term/ARM model is missing');
const js = ts.transpileModule(fs.readFileSync('loan-options.ts', 'utf8'), { compilerOptions: { module: ts.ModuleKind.CommonJS } }).outputText;
const sandbox = { exports: {} };
vm.runInNewContext(js, sandbox);
const { parseLoanYears } = sandbox.exports;
assert.equal(parseLoanYears('25'), 25);
assert.equal(parseLoanYears(' 40 '), 40);
for (const value of ['', '0', '51', '-5', '2.5', '25years', 'Infinity']) assert.equal(parseLoanYears(value), null);
console.log('PASS: custom terms accept whole years 1–50 and reject malformed input');
const { monthlyPrincipalAndInterest, armScenario } = sandbox.exports;
assert.equal(typeof armScenario, 'function', 'ARM scenario calculation is missing');
assert.equal(monthlyPrincipalAndInterest(300000, 0, 25), 1000);
assert.equal(monthlyPrincipalAndInterest(0, 6.5, 30), 0);
const initial = monthlyPrincipalAndInterest(360000, 6.5, 30);
// Independent month-by-month amortization verifies the balance at first reset.
let remaining = 360000;
for (let month = 0; month < 84; month++) remaining = remaining * (1 + 6.5 / 1200) - initial;
const scenario = armScenario(360000, 6.5, 30, 7, '8.5');
assert.ok(Math.abs(scenario.balance - remaining) < 0.000001);
assert.ok(Math.abs(scenario.payment - monthlyPrincipalAndInterest(remaining, 8.5, 23)) < 0.000001);
assert.equal(scenario.month, 85);
assert.ok(Math.abs(armScenario(360000, 6.5, 30, 7, '6.5').payment - initial) < 0.000001);
assert.equal(armScenario(300000, 0, 25, 5, '0').payment, 1000);
for (const rate of ['', '-1', '101', 'abc', '5.5.5']) assert.equal(armScenario(360000, 6.5, 30, 7, rate), null);
assert.equal(armScenario(360000, 6.5, 7, 7, '8'), null);
assert.equal(armScenario(360000, 6.5, 5, 7, '8'), null);
console.log('PASS: initial amortization and first-reset scenarios (same/higher/zero rates, invalid inputs)');
